name: Release CI
on:
  push:
    branches:
      - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn
      - name: Install lint
        run: yarn add eslint
      - name: init lint
        run:  npm init @eslint/config
      - name: Run lint command
        run: yarn run eslint ./src/
  release:
    needs: [lint]
    name: Build and release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install        
      - name: Run build command
        run: npm run build
      - name: Run Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: "haisheng Bot"
          GIT_AUTHOR_EMAIL: "edwin.uestc@gmail.com"
          GIT_COMMITTER_NAME: "haisheng Bot"
          GIT_COMMITTER_EMAIL: "edwin.uestc@gmail.com"
